# Generated by Django 5.1.4 on 2025-01-20 05:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patientInfo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="eyeinfo",
            name="diabetic_retinopathy_discription",
            field=models.TextField(blank=True, null=True, verbose_name="糖尿病视网膜病变具体描述"),
        ),
        migrations.AddField(
            model_name="eyeinfo",
            name="glaucoma_discription",
            field=models.TextField(blank=True, null=True, verbose_name="青光眼具体描述"),
        ),
        migrations.AddField(
            model_name="eyeinfo",
            name="nasolacrimal_duct_discription",
            field=models.TextField(blank=True, null=True, verbose_name="鼻泪管其他描述"),
        ),
        migrations.AddField(
            model_name="eyeinfo",
            name="other_final_tear_duct_diagnosis_discription",
            field=models.TextField(blank=True, null=True, verbose_name="其他泪道病最终诊断具体描述"),
        ),
        migrations.AddField(
            model_name="eyeinfo",
            name="other_ocular_diseases_other_discription",
            field=models.TextField(blank=True, null=True, verbose_name="其他眼部疾病其他具体描述"),
        ),
        migrations.AddField(
            model_name="eyeinfo",
            name="uveitis_discription",
            field=models.TextField(blank=True, null=True, verbose_name="色素膜炎具体描述"),
        ),
        migrations.AlterField(
            model_name="baseinfo",
            name="age",
            field=models.IntegerField(null=True, verbose_name="年龄"),
        ),
    ]
