# Generated by Django 5.1.4 on 2025-01-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patientInfo", "0002_eyeinfo_diabetic_retinopathy_discription_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eyeinfo",
            name="tear_duration_months",
            field=models.FloatField(null=True, verbose_name="溢泪持续时间（月）"),
        ),
    ]
